# Generated by Django 5.1.6 on 2025-03-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=16, null=True)),
                ('year', models.DateField(null=True)),
                ('genre', models.CharField(max_length=16, null=True)),
                ('count', models.IntegerField(null=True)),
                ('is_available', models.BooleanField(null=True)),
            ],
        ),
    ]
